version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: place-to-relax-api
        restart: unless-stopped
        ports:
            - '8000:8000'
        volumes:
            - ./:/var/www/html
        depends_on:
            - database
    database:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: sputnik
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data


